### PR TITLE
feat: copy map image to the clipboard

### PR DESCRIPTION
**Pull request by n1ru4l**
👀

Requires chrome >= 76 AFAI. We might simply hide it for other browsers or use some kind of feature detection.

Closes https://github.com/dungeon-revealer/dungeon-revealer/issues/414

image

### CODE REVIEW

**Comment by jonhoo** [comment]
Oooooh, that's awesome! Any idea whether it'll also work on latest Firefox (which is what I personally use)? And if not, what it might take to get that to work.

This will make online play through Discord _so_ much nicer.

Just to clarify, this copies the _masked_ (player-visible) map to the clipboard, right — not the full map?

**Comment by n1ru4l** [comment]
Yes it copies the player map, as you cans ee hear we write the map and the map fog to a new canvas:

https://github.com/dungeon-revealer/dungeon-revealer/pull/415/files#diff-bb4e14c00e955a5b242220cffb038be4R949-R955


Regarding Firefox: https://caniuse.com/#feat=mdn-api_clipboard_write

it does not look that good for other browsers :/

**Comment by n1ru4l** [comment]
ON other browsers we could fallback to opening a base64 image string in a new tab:

image

**Comment by jonhoo** [comment]
Oh, yeah, that sounds like a good idea! Though I'd worry it might not work for very large maps (I have one that's like 5MB for example)..

**Comment by n1ru4l** [comment]
on other browsers, we could fallback to opening the base64 string of the image in a new tab 

image

**Comment by n1ru4l** [comment]
> Oh, yeah, that sounds like a good idea! Though I'd worry it might not work for very large maps (I have one that's like 5MB for example)

Hm, we could shave some off by using jpeg instead of png when reading the image from the canvas. I just pushed the Firefox commit.

Could you try it out and provide some Feedback regarding larger maps?

**Comment by jonhoo** [comment]
I think it'd be better to feature-test this rather than check the browser. Especially since it's pretty easy to enable it in Firefox. I may not get around to actually testing this for a little while, but will keep a tab open for when I get a chance!

**Comment by maxb2** [comment]
> Could you try it out and provide some Feedback regarding larger maps?

I threw a 100MB image at it in both browsers on Linux. They both worked just fine. Chrome outputs a ~5MB png. The jpeg output in Firefox does cut the size down to ~2MB. Pasting from the clipboard is way nicer, I've got to say.

**Comment by n1ru4l** [comment]
The 100 mb image will be "down-scaled" upon loading:

https://github.com/apclary/dungeon-revealer/blob/79d90a828c44964c77b94b744043c25f09134757/src/dm-area/dm-map.js#L813-L828

So it makes sense that the output is way smaller.

> Pasting from the clipboard is way nicer, I've got to say.
I agree that pasting from the clipboard is definitely nicer, but we gotta work with what we have :D

> I think it'd be better to feature-test this rather than check the browser.

Yes, you are right.

**Pull request merged**
