### PR TITLE
feat: Add dice notation to drop Lowest or Highest rolls

### PR DESCRIPTION
**Pull request by PurpleGranite**
Drop the highest roll by suffixing `-H`, example: `[2d20-H]` - useful to roll with disadvantage.

Drop the lowest roll by suffixing `-L`, example: `[2d20-L]` or `[4d6-L]` - useful to roll with advantage, or when rolling character stats.

### CODE REVIEW

**Comment by PurpleGranite** [comment]
Ah, good point.  I'd taken the notation from https://en.wikipedia.org/wiki/Dice_notation#Selective_results where the `-H` / `-L` options are described, but completely understand wanting to keep similarity with the closer competition.  There's probably no harm in implementing both options, so long as they're both well documented.

I'd stray away from using colour or greying-out the dice rolls for accessibility reasons.  I'd considered implementing a ~~strikethrough~~ for the dropped dice, but that was a bit more complex than the basic implementation so far, so wanted to be sure there was appetite for implementing this kind of feature before doing that.

Happy to go ahead and update the syntax, and look at also clearly showing the dropped dice if that sounds like a good approach.

**Comment by maxb2** [comment]
I've seen other apps use `^` and `v` to mean take the highest and lowest respectively. 

For example:
`2d20^1` for DnD advantage.

As a more general example:
 `8d4v4` to take the 4 lowest rolls.

**Comment by PurpleGranite** [comment]
It should be pretty straightforward to implement the `^` / `v` syntax as well - would be good to provide several familiar options, to support as many folk transitioning over as possible.

**Comment by maxb2** [comment]
[Avrae](https://avrae.io/) (DnDBeyond Discord bot) uses `kh`/`kl` for keep highest/lowest. It seems like everybody does it differently =/

**Comment by n1ru4l** [comment]
The representation here is actually quite nice I think: https://wiki.roll20.net/Dice_Reference#Drop.2FKeep (greyish color)

**Comment by PurpleGranite** [comment]
The problem I see with that is that the colour contrast is too low for people with visual impairments.  The equivalent opaque foreground colours for the dropped rolls in that example are `#999999` (for non-crits), `#C79B9B` (for crit-fail) and `#A7C79B`, all of which fall well below WCAG 2.1 AA colour contrast ratio of 4.5:1 for normal text (text below 16pt), with contrasts of 2.84:1, 2.44:1 and 1.86:1 respectively, when used on a white background.

I think it must be possible to find a better approach that is more inclusive - D&D after all is played by a very wide range of people, including those with various disabilities, so tools like this should surely be trying to support as wide a range of those as possible? (Full disclosure, I'm one of those sight impaired players!)

**Comment by n1ru4l** [comment]
@PurpleGranite I totally agree with you on that! If you have any recommendations feel free to share/implement it.

**Comment by PurpleGranite** [comment]
I made progress implementing the different roll notations last night - I'll get that out of the way first and posted for review, then move on to looking at the display options.  I'm thinking something like - `17 (d20) + 10 (d20) (dropped: 5 (d20), 4 (d20)) = 27` (for `[4d20k2]`) - I just need to work out how to get the dropped rolls over to the chat system for display.

**Comment by PurpleGranite** [comment]
That's the rolling rules discussed above now in place - quite a challenge because of limitations in the upstream library, but all should be working now.

To summarise, the rolling options now are:
| roll | result
|------|--------|
| `[XdY-L]` | Roll `X` d`Y`'s, drop the lowest |
| `[XdY-H]` | Roll `X` d`Y`'s, drop the highest |
| `[XdY^N]` | Roll `X` d`Y`'s, keep the highest `N` |
| `[XdYkN]` | ""   "" |
| `[XdYkhN]` | ""   "" |
| `[XdYvN]` | Roll `X` d`Y`'s, keep the lowest `N` |
| `[XdYklN]` | ""   "" |
| `[XdYdN]` | Roll `X` d`Y`'s, drop the lowest `N` |
| `[XdYdlN]` | ""   "" |
| `[XdYdhN]` | Roll `X` d`Y`'s, drop the highest `N` |

**Comment by PurpleGranite** [comment]
Next on the list - displaying dropped vs kept dice.

**Comment by n1ru4l** [comment]
Hit me up on discord or here if you have any relay/graphql related questions!

**Comment by n1ru4l** [comment]
Hey, @PurpleGranite Thanks for starting this! I picked your code and refactored it a bit in https://github.com/dungeon-revealer/dungeon-revealer/pull/1226

**Comment by PurpleGranite** [comment]
Thanks @n1ru4l - apologies for effectively dropping it, work got pretty hectic - glad it turned out to be useful as a starting point :)

**Pull request closed without merging**
