### PR TITLE
Github Actions for CI/CD

### LINKED ISSUE #182: Windows executable silently exits
Since [v1.2.0](https://github.com/apclary/dungeon-revealer/releases/tag/v1.2.0) the Windows executable silently exits without starting the server software. There aren't any error messages. I tested the executables on a Windows 10 machine. The last version that works is [v1.1.0](https://github.com/apclary/dungeon-revealer/releases/tag/v1.1.0).

### PR DESCRIPTION
**Pull request by maxb2**
This PR completes the migration of our CI/CD from Travis to Github Actions.

Fixes #182, allows #254 to be merged, and phases out Travis.

Features:

- **Checks.** Branch and Pull Request checks are performed for node.js versions `10.x` and `12.x`. 
- **Compilation.** x64 binaries are compiled in their native operating systems instead of using cross compilation on Linux. Compiling natively in Windows fixes #182. 
- **Deployment.** On a tagged branch, a draft release is created and has the packages automatically uploaded to it.

Todo:
- [x] Pull Request checks
- [x] Branch checks
- [x] Build and deploy x64 binaries
- [x] Build and deploy arm binary
- [x] Build and deploy docker containers
- [ ] Set Dockerhub credentials as [secrets](https://help.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets)
- [ ] Remove Travis checks from the repository

### CODE REVIEW

**Comment by n1ru4l** [comment]
@maxb2 Do you think it is also easily possible to automatically create a git tag in case the package.json version has changed on master?

**Comment by maxb2** [comment]
@n1ru4l There is an action to [bump the version](https://github.com/marketplace/actions/github-tag-bump).  However, the only way I can think of to bump the version based on package.json is writing something to parse the file itself and then comparing it with a previous commit. I think manually making a tag locally and then pushing it would be way easier. Right now, the binary builds only trigger on a tag.

For example:
```
git commit -m v1.6.0
git tag v1.6.0
git push && git push --tags
```

**Comment by maxb2** [comment]
@apclary, can you set the `DOCKER_USERNAME` and `DOCKER_PASSWORD` secrets to your Dockerhub credentials? The steps are [here](https://help.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets#creating-encrypted-secrets). This can be merged after you do that.

@n1ru4l, you can remove the Travis checks right before this is merged.

**Comment by n1ru4l** [comment]
@apclary Could you please update the secrets, this is the only thing that is blocking the merge right now 😇

**Comment by maxb2** [comment]
@n1ru4l, should I split the CI/CD responsibilities between Actions and Travis until @apclary returns?
Travis would handle branch/PR checks, and deploy docker images to Dockerhub. Actions would also perform branch/PR checks but be solely responsible for the executable deployment.

**Comment by n1ru4l** [comment]
@maxb2 Yes please! I hope you all are doing well given the circumstances 😕

**Comment by n1ru4l** [comment]
@maxb2 I think we can close this now?

**Comment by maxb2** [comment]
Closed in favor of #407

**Pull request closed without merging**
