### PR TITLE
feat: add area descriptions

### LINKED ISSUE #181: Map Notes
It would be awesome if the DM could position a token in each area on a map. Upon clicken on the token a sidebar opens with some notes related to that location, the DM could write down a text he wants to read to the players or the enemies that are present in that location or the items available.

This would be very handy for preparing modules without having to flick through the book all the time.

Of course, those tokens (and the info) should only be visible to the DM.

### LINKED ISSUE #198: token context menu: limit to viewport
The context menu should be limited by the viewport.

### PR DESCRIPTION
**Pull request by n1ru4l**
Early-stage, but I will use this for my game tomorrow.

Screenshot 2019-10-17 at 20 17 36

Screenshot 2019-10-17 at 20 17 46

- [x] lock a token
- [x] select token type: entity or area
- [x] open area token window on the right side of the screen upon clicking
- [x] add a token title (for tokens of type area)
- [x] add a token description (for tokens of type area) (via markdown editor)

**TODO 2019/02/09**

- [x] empty states
- [x] Link existing note to a token
- [x] Keep Token Reference Aside state and note state in sync (probably will incorporate some new state using mobx to simplify all the logic with auto-save etc.)
- [x] Note Editor Preview
- [x] Change Note title in the Note Editor

___

Closes #181
Fixes #198

### CODE REVIEW

**Comment by thorgod** [comment]
Wow that looks really cool!

**Comment by AlchemicalAgent** [comment]
Did you end up running this for your game? How did it work out?
Looks great!

**Comment by n1ru4l** [comment]
> Did you end up running this for your game? How did it work out?
Looks great!

Yes, I used it last week, worked very well for me. Unfortunately, the player section was broken on iOS so my players could not use it 😅.

However, tonight I gonna do the second part for Death House and this time everything should work as expected.

> So the difference between entity and area tokens is that area tokens have a title and clicking them opens a description text box?

Yes! I still wanna decouple the description and title from the token itself. So that a token only references a "note" (or later a different entity). My main concern is that someone accidentally deletes a token and loses all the text they added to this (did not happen to me yet 😂).

Also, the editor needs some more work. Gonna put in some more work over the next few weeks.

**Comment by apclary** [comment]
Is this ready to go in?

**Comment by n1ru4l** [comment]
@apclary Nope, finally had some spare time and motivation to continue shaping this into the directions i want to head into. Still some more work to do.

**Comment by n1ru4l** [comment]
Quick update: This is almost finished... Only thing that is missing is linking an existing note to a a token.

**Comment by n1ru4l** [comment]
Done 🔥

**Pull request merged**
